version: '2'
services:
  web:
    image: website:0.1
    build: .
    ports:
      - 81:80
      - 443:5001
    env_file:
      - db.env
    # entrypoint: ./start.pl --init --command shotgun
    depends_on:
      - db
    networks:
      - frontend
      - backend
  db:
    image: mysql:5.7
    env_file:
      - db.env
    networks:
      - backend
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
